title: Rohit Yadav
author: Rohit Yadav
email: rohit@yadv.in
description: >
  Blog posts and talks by Rohit Yadav.

baseurl: ""
url: http://rohityadav.cloud
#enforce_ssl: rohityadav.cloud

timezone: Asia/Kolkata
encoding: "utf-8"
exclude: ['README.markdown']

permalink: blog/:title/

collections:
  algorithms:
    output: true
    permalink: /algorithms/:path

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
